name: simple_dart_view_controller
description: Library for creating a single page application on Dart.
version: 0.0.1
repository: https://github.com/simple-dart/view_controller
platforms:
  web:


environment:
  sdk: '>=2.18.0 <3.0.0'

dev_dependencies:
  build_runner: ^2.3.2
  build_web_compilers:
  test: